### ISSUE TITLE
Accurate Linux Support

### ISSUE THREAD

**Issue by mtunixic** [UnderminersTeam/UndertaleModTool#2161]
### Which component should be improved?

Compiler

### Describe your feature suggestion in more detail

this is minor but why is it specifically called ubuntu when it's just the default format for linux in general?
thanks for your time

**Comment by MTUnixic** [comment]
> Where is "Ubuntu" written exactly?

oh it's in the assets

**Comment by CST1229** [comment]
i think you mean the filenames of CLI releases (both release and bleeding edge):
![Image](https://github.com/user-attachments/assets/2fa8d55c-3a9a-4eef-b376-8042de3e399e)

(i assume the filename comes from the Actions CLI builds, where an Ubuntu runner is used to build the Linux version, and the OS name is added to the filename)

**Comment by VladiStep** [comment]
Oh, I see it now, and I also want to know why it's like that:
```yml
name: Publish CLI

on:
 #push:
 #  branches: [ master ]
  workflow_dispatch:

jobs:
  publish_cli:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        configuration: [Debug]
        bundled: [true, false]
        include:
          - os: ubuntu-latest
            rid: linux-x64
          - os: macOS-latest
            rid: osx-x64
          - os: windows-latest
            rid: win-x64
```

Because for actual build command (`dotnet publish`) it uses `rid`, so it will be "linux-x64"
